name: Deploy Docs
on:
 push:
   branches: [main]
 workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r doc_requirements.txt
      - run: mkdocs build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: 'site'
      - id: deployment
        uses: actions/deploy-pages@v1