# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

env:
  POETRY_VIRTUALENVS_PREFER_ACTIVE_PYTHON: true

jobs:
  Lint-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Poetry
      run: pipx install poetry
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "poetry"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
    - name: Poetry in matfact
      run: cd matfact && poetry install
    - name: Poetry in HMM
      run: cd hmm_synthetic && poetry install
    - name: Poetry in bokeh_app
      run: cd bokeh-demo && poetry install
    - name: Poetry in processing
      run: cd processing && poetry install
    - name: Run pre-commit
      run: |
        pre-commit run --all-files
    - name: Test matfact with pytest
      run: |
        cd matfact
        poetry run pytest -Wignore
    - name: Test HMM with pytest
      run: |
        cd hmm_synthetic
        poetry run pytest -Wignore
    - name: test processing with pytest
      run : |
        cd processing
        poetry run pytest -Wignore